LDLIBS=-lcurses
SRCS=\
Ex1_server.c	\
Ex1_client.c	\
Ex2_server.c	\
Ex2_client.c	\
Ex3a_server.c	\
Ex3a_client.c	\
Ex3b_server.c	\
Ex3b_client.c	\
Ex3c_server.c	\
Ex3c_client.c	\
Ex3d_server.c	\
Ex3d_client.c	\

EXES=$(SRCS:.c=)

all:$(EXES)
